[package]
name = "kterminal"
version = "0.1.0"
authors = ["kaigonzalez <gkai70264@gmail.com>"]
edition = "2018"


[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
reqwest = "0.11"
ncurses = "5.101.0"